#
# 2023-09-02	dwalker		Initial Version
#
PERL=/opt/local/bin/perl
AUTH="Derrik Walker"
BundleID="org.doomy.Application"

bytecount:
	platypus -D -a "Byte Count" -o 'Text Window' -p ${PERL} -I ${BundleID} -u ${AUTH} -V 1.0 bytecount.pl

hexdump:
	platypus -D -a "Hexdump" -o 'Text Window' -p ${PERL} -I ${BundleID} -u ${AUTH} -V 1.0  hexdump.pl 
